name: build

on:
  push:
    branches: [main]
    paths:
      - app/**
      - .github/workflows/build.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  image:
    uses: ./.github/workflows/image.yml
    with:
      dir: app
      image: ghcr.io/protopiatech-labs/shop
